name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build:production
        
      - name: Create plugin ZIP
        run: |
          mkdir plugin-dist
          cp main.js manifest.json plugin-dist/
          (cd plugin-dist && zip ../obsidian-biblelink.zip main.js manifest.json)

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: ./obsidian-biblelink.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 